// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nybatvzxejhcxzkgymkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55YmF0dnp4ZWpoY3h6a2d5bWtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTkyNTEsImV4cCI6MjA2ODQ5NTI1MX0.rFWPZ2lJ52eFLVOzzsOOCc3zbkamg2We_4819pe1Bo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});